services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sirsi-api
    ports:
      - "8001:8001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: