// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cadastrar/vagas": {
            "post": {
                "description": "Registra uma novo vaga no banco",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Create Jobs"
                ],
                "summary": "Criar uma nova vaga",
                "parameters": [
                    {
                        "description": "Dados da vaga",
                        "name": "job",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.Job"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Vaga criado com sucesso",
                        "schema": {
                            "$ref": "#/definitions/dtos.Message"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIError"
                        }
                    }
                }
            }
        },
        "/jobs": {
            "get": {
                "description": "Retorna todas as vagas diponíveis no Banco (Colletion Testes)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Retorna vagas",
                "responses": {
                    "201": {
                        "description": "Vagas retornadas com sucesso!",
                        "schema": {
                            "$ref": "#/definitions/dtos.Message"
                        }
                    },
                    "400": {
                        "description": "Erro ao retornar as vagas",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIError"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Registra um novo usuário na API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Criar um novo usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Usuário criado",
                        "schema": {
                            "$ref": "#/definitions/dtos.Message"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "$ref": "#/definitions/dtos.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.APIError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "dtos.Job": {
            "type": "object",
            "properties": {
                "descricao": {
                    "type": "string"
                },
                "localizacao": {
                    "type": "string"
                },
                "posted:": {
                    "type": "string"
                },
                "titulo": {
                    "type": "string"
                }
            }
        },
        "dtos.Message": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dtos.User": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Value: Bearer abc... (Bearer+space+token)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Autenticação e Tarefas SIRSI",
	Description:      "API do Sistema de Recrutamento e Seleção Inteligente (SIRSI)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
